### ISSUE TITLE
What about adding pandas and Pillow has dependencies

### ISSUE THREAD

**Issue by picca** [Codra-Ingenierie-Informatique/guidata#58]
Hello,

I need to patch the setup.cfg and add pandas and Pillow dependencies in order to pass the tests.

+        pandas
+        Pillow

**Comment by PierreRaybaut** [comment]
This should be fixed with v3.0.1, especially since revision e13da7f2bdb8655323258296196337460a41bc1b.

**Comment by picca** [comment]
so these dependencies are optional right ?

**Comment by PierreRaybaut** [comment]
Absolutely
