### ISSUE TITLE
[3.0.1] pyproject.toml/setuptools: automatic package discovery does not work on debian

### ISSUE THREAD

**Issue by picca** [Codra-Ingenierie-Informatique/guidata#60]
In order to build guidata I need to add this in pyproject.toml

```
+[tool.setuptools.packages.find]
+include = ["guidata*"]
+
```

If not it finds multiple directory guidata and debian and understand that this is a multiple package project.
I think that it will be the same when you will re-add the doc directory.

**Comment by PierreRaybaut** [comment]
Thanks for your feedback fred!

I think that Python package management has never been worse... 
Using setuptools and the new official way (pyproject.toml) is a nightmare.
Unfortunately, using setuptools is my only option since I need to use the same solution with all my projects and some of them (e.g. guiqwt) have C++ extensions.

**Comment by picca** [comment]
pyfai switch to mesonpy like numpy, and next scipy.

I think that at the end this will be the officiel way to build most of c/c++ extensions...

here the link https://github.com/silx-kit/pyFAI

> I think that Python package management has never been worse...

I prefer the new pyproject whuich is more declarativ.
the problem with setup.py was thaht so many peoples where customizing it and it was a nightmare for packager ;)

> Using setuptools and the new official way (pyproject.toml) is a nightmare.
> Unfortunately, using setuptools is my only option since I need to use the same
> solution with all my projects and some of them (e.g. guiqwt) have C++
> extensions.

One problématic area is the package data which are not installed in the package directory.
at least in haskell there is a dedicated method common to all package in order to find the data once installed...


Cheers

Just for info when will be release datalab ? and are you aware of this 

https://datalab.sspcloud.fr/home

**Comment by PierreRaybaut** [comment]
Again, our minds are somehow connected :).

I did some tests with mesonpy and it seems that it could be the right long-term solution indeed.
But, for now, as I have a solution that works, I will stick with setuptools for a while. I think I will get back to this in a few months or so. So, definitely, mesonpy should be my final choice.

**Comment by PierreRaybaut** [comment]
Regarding DataLab, I'm not sure: hopefully in September? It depends on a financial support that we are currently working on.

There are multiple projects called DataLab out there: that is quite a generic term actually. So we chose DataLab in spite of this situation and we do not pretend that this will be *the* DataLab, but just *a* DataLab among others.
