### ISSUE TITLE
[3.0.2] there is no more guidata-test script

### ISSUE THREAD

**Issue by picca** [Codra-Ingenierie-Informatique/guidata#63]
It seems that this scripts a disparu :) during the conversion.

Cheers

**Comment by picca** [comment]
It would be great if you could add this file in the source

https://salsa.debian.org/science-team/guidata/-/blob/master/debian/guidata-tests3.desktop

for info the Exec TryExec should macth with the name of the guidata-test script :)

This way the desktop file could be identical from one distribution to the other.

**Comment by PierreRaybaut** [comment]
> 

Do you want it to be placed in a new "debian" folder at the root of the repo?

**Comment by picca** [comment]
Hello Pierre,

I do not know, this is something related to xdg

https://www.freedesktop.org/wiki/Specifications/desktop-entry-spec/

So it is not Debian specific...

what about an extra xdg directory with all the xdg files ?

**Comment by PierreRaybaut** [comment]
See #64
