### ISSUE TITLE
Add guidata-tests.desktop file to repository

### ISSUE THREAD

**Issue by PierreRaybaut** [Codra-Ingenierie-Informatique/guidata#64]
See here:
https://github.com/Codra-Ingenierie-Informatique/guidata/issues/63#issuecomment-1654631835

**Comment by PierreRaybaut** [comment]
@picca :
Is it ok if I rename the file to "guidata-tests.desktop" and that the contents are the following:
```
[Desktop Entry]
Version=1.0
Type=Application
Name=guidata-tests
GenericName=guidata test application
Comment=you can use this applications to test all guidata features.
TryExec=guidata-tests
Exec=guidata-tests
Icon=guidata.svg
Categories=Education;Science;Physics;
```
(because there is no longer Python 2 support)

**Comment by PierreRaybaut** [comment]
Where should I put it in the repository?
(in a new "debian" folder?)

**Comment by PierreRaybaut** [comment]
I think that I'll simply put it at the root of the repository, for now.

**Comment by picca** [comment]
There is only one file right :))

**Comment by PierreRaybaut** [comment]
Ok, I hope that's ok for v3.0.4 this time :)

**Comment by picca** [comment]
I have difficultis with the qt_documentation extension.

I need to deactivated it becaus ewe do not have the intersphinx available for PyQt5...

I already filled a buf report about this at Debian.

But I manage this :))
cheers
